### ISSUE TITLE
Actividad 7 Juicio Experto y Costos

### ISSUE THREAD

**Issue by Valentiin01** [SistemasTecTlaxiaco/actividad-7-juicio-experto-y-costos-entrevista_equipo-german#1]
[GREGORIO,GERMAN,GENARO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-juicio-experto-y-costos-entrevista_equipo-german/files/13301098/GREGORIO.GERMAN.GENARO.pdf)

**Comment by EdwinOrtiz1412** [comment]
30 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
